version: '3.8'

services:
  vue:
    build:
    context: .
    ports:
    - 3000:3000
    command: npm run debug
    networks:
      - default

  jenkins:
    container_name: jenkins
    restart: always
    image: jenkins/jenkins:lts
    ports:
      - 8080:8080
    volumes:
      - jenkins-home:/var/jenkins_home
    networks:
      - default
volumes:
  jenkins-home:

networks:
  default:
    name: ethernet
    external: true


  

 
